services:
  - type: web
    name: top50songs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      alembic upgrade head
      gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: top50songs_db
          property: connectionString
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: top50songs_db
    databaseName: top50songs
    plan: free
