services:
  - type: web
    name: top50songs
    runtime: python
    repo: https://github.com/wchadzynski23/top50songs
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: top50songs-db
          property: connectionString
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
    autoDeploy: false
    healthCheckPath: /
    numInstances: 2

databases:
  - name: top50songs-db
    databaseName: top50songs
    plan: starter
    ipAllowList: []
    dailyBackup: true
    user: top50songs_user
    version: "14"
